package net.folfas.quickapp.api.intellij;

public class IntellijStaticResponse {

    public static String getResponse() {

        return "{\n"
            + "  \"dependencies\": {\n"
            + "    \"type\": \"hierarchical-multi-select\",\n"
            + "    \"values\": []\n"
            + "  },\n"
            + "  \"type\": {\n"
            + "    \"type\": \"action\",\n"
            + "    \"default\": \"maven-project\",\n"
            + "    \"values\": [\n"
            + "      {\n"
            + "        \"id\": \"maven-project\",\n"
            + "        \"name\": \"ignored\",\n"
            + "        \"description\": \"ignored\",\n"
            + "        \"action\": \"/download\",\n"
            + "        \"tags\": {\n"
            + "          \"build\": \"maven\",\n"
            + "          \"format\": \"project\"\n"
            + "        }\n"
            + "      }\n"
            + "    ]\n"
            + "  },\n"
            + "  \"packaging\": {\n"
            + "    \"type\": \"single-select\",\n"
            + "    \"default\": \"jar\",\n"
            + "    \"values\": [\n"
            + "      {\n"
            + "        \"id\": \"jar\",\n"
            + "        \"name\": \"ignored\"\n"
            + "      }\n"
            + "    ]\n"
            + "  },\n"
            + "  \"javaVersion\": {\n"
            + "    \"type\": \"single-select\",\n"
            + "    \"default\": \"1.8\",\n"
            + "    \"values\": [\n"
            + "      {\n"
            + "        \"id\": \"1.8\",\n"
            + "        \"name\": \"ignored\"\n"
            + "      }\n"
            + "    ]\n"
            + "  },\n"
            + "  \"language\": {\n"
            + "    \"type\": \"single-select\",\n"
            + "    \"default\": \"java\",\n"
            + "    \"values\": [\n"
            + "      {\n"
            + "        \"id\": \"java\",\n"
            + "        \"name\": \"ignored\"\n"
            + "      }\n"
            + "    ]\n"
            + "  },\n"
            + "  \"bootVersion\": {\n"
            + "    \"type\": \"single-select\",\n"
            + "    \"default\": \"2.1.6.RELEASE\",\n"
            + "    \"values\": [\n"
            + "      {\n"
            + "        \"id\": \"2.1.6.RELEASE\",\n"
            + "        \"name\": \"ignored\"\n"
            + "      }\n"
            + "    ]\n"
            + "  },\n"
            + "  \"groupId\": {\n"
            + "    \"type\": \"text\",\n"
            + "    \"default\": \"ignored\"\n"
            + "  },\n"
            + "  \"artifactId\": {\n"
            + "    \"type\": \"text\",\n"
            + "    \"default\": \"ignored\"\n"
            + "  },\n"
            + "  \"version\": {\n"
            + "    \"type\": \"text\",\n"
            + "    \"default\": \"ignored\"\n"
            + "  },\n"
            + "  \"name\": {\n"
            + "    \"type\": \"text\",\n"
            + "    \"default\": \"demo\"\n"
            + "  },\n"
            + "  \"description\": {\n"
            + "    \"type\": \"text\",\n"
            + "    \"default\": \"Demo project for Spring Boot\"\n"
            + "  },\n"
            + "  \"packageName\": {\n"
            + "    \"type\": \"text\",\n"
            + "    \"default\": \"ignored\"\n"
            + "  }\n"
            + "}";
    }
}
