language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - ./gradlew build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cp src/main/docker/Dockerfile build/libs
  - docker build -t folfix/quick-app build/libs
  - export GIT_SHORT=$(git rev-parse --short HEAD)
  - docker tag folfix/quick-app folfix/quick-app:$GIT_SHORT
  - docker push folfix/quick-app:$GIT_SHORT
  - docker push folfix/quick-app:latest
