language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk11

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build
    - stage: docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t folfix/quick-app -f src/main/docker/Dockerfile build/libs
        - docker push folfix/quick-app

